version = 1

[modules."rrr::basetypes"]
namespace = "rrr"

[modules."rrr::basetypes".symbols."SparseInt::buf_size"]
kind = "function"
callable_signatures = ["size_t(uint8_t)"]

[modules."rrr::basetypes".symbols."SparseInt::dump32"]
kind = "function"
callable_signatures = ["size_t(int32_t,uint8_t*)"]

[modules."rrr::basetypes".symbols."SparseInt::dump64"]
kind = "function"
callable_signatures = ["size_t(int64_t,uint8_t*)"]

[modules."rrr::basetypes".symbols."SparseInt::load32"]
kind = "function"
callable_signatures = ["int32_t(const uint8_t*)"]

[modules."rrr::basetypes".symbols."SparseInt::load64"]
kind = "function"
callable_signatures = ["int64_t(const uint8_t*)"]

[modules."rrr::basetypes".symbols.Time]
kind = "type"
callable_signatures = []

[modules."rrr::basetypes".symbols."Time::now"]
kind = "function"
callable_signatures = ["uint64_t(bool)"]

[modules."rrr::logging"]
namespace = "rrr"

[modules."rrr::logging".symbols.log_line]
kind = "function"
callable_signatures = ["void(int32_t,int32_t,const int8_t*,const std::string&)"]

[modules."rrr::reactor"]
namespace = "rrr"

[modules."rrr::reactor".symbols.create_sp_box_event]
kind = "function_template"
callable_signatures = ["rusty::Arc<BoxEvent<T>>()"]

[modules."rrr::reactor".symbols.Fiber]
kind = "type"
callable_signatures = []

[modules."rrr::reactor".symbols.IntEvent]
kind = "type"
callable_signatures = []

[modules."rrr::reactor".symbols.create_sp_int_event]
kind = "function"
callable_signatures = ["rusty::Arc<IntEvent>(int32_t)"]

[modules."rrr::reactor".symbols."IntEvent::set"]
kind = "method"
callable_signatures = ["int32_t(int32_t)"]

[modules."rrr::reactor".symbols."IntEvent::wait"]
kind = "method"
callable_signatures = ["void()"]

[modules."rrr::reactor".symbols."Fiber::current_fiber"]
kind = "method"
callable_signatures = ["rusty::Option<rusty::Rc<Fiber>>()"]

[modules."rrr::reactor".symbols."Fiber::yield_"]
kind = "method"
callable_signatures = ["void()"]

[modules."rrr::reactor".symbols.fiber_sleep]
kind = "function"
callable_signatures = ["void(uint64_t)"]

[modules."rrr::reactor".symbols.pollworker_is_on_poll_thread]
kind = "function"
callable_signatures = ["bool()"]

[modules."rrr::reactor".symbols.PollThread]
kind = "type"
callable_signatures = []

[modules."rrr::reactor".symbols."PollThread::add_proxy"]
kind = "method"
callable_signatures = ["void(PollableProxy)"]

[modules."rrr::reactor".symbols."PollThread::update_mode"]
kind = "method"
callable_signatures = ["void(int32_t,int32_t)"]

[modules."rrr::debugging"]
namespace = "rrr"

[modules."rrr::debugging".symbols.verify]
kind = "function_template"
callable_signatures = ["void(bool)"]

[modules."rrr::errors"]
namespace = "rrr"

[modules."rrr::serializable"]
namespace = "rrr"

[modules."rrr::serializable".symbols.serializable_holder_of]
kind = "function_template"
callable_signatures = ["const Holder<T>*(const SerializableBase*)"]

[modules."rrr::serializable".symbols."SerializableRegistry::create"]
kind = "function"
callable_signatures = ["SerializableProxy(int32_t)"]

[modules."rrr::serializable".symbols.BinaryWriteArchive]
kind = "type"

[modules."rrr::serializable".symbols.BinaryReadArchive]
kind = "type"

[modules."rrr::serializable".symbols.SerializableBase]
kind = "type"

[modules."rrr::serializable".symbols."details::SerializableSharedPtrHolder"]
kind = "type_template_constructor"
callable_signatures = ["details::SerializableSharedPtrHolder<T>(rusty::Arc<T>)"]

[modules."rrr::serializable".symbols."Serialize_::serialize"]
kind = "function_template"
callable_signatures = ["void(const std::string&,BinaryWriteArchive&)"]

[modules."rrr::serializable".symbols."Deserialize_::deserialize"]
kind = "function_template"
callable_signatures = ["void(std::string&,BinaryReadArchive&)"]

[modules.rusty]
namespace = "rusty"

[modules.rusty.symbols."Arc::get"]
kind = "method"
callable_signatures = ["const T*()"]

[modules.rusty.symbols.arc_make_default]
kind = "function_template"
callable_signatures = ["rusty::Arc<T>()"]

[modules.std]
namespace = "std"

[modules.std.symbols.make_pair]
kind = "function_template"
callable_signatures = ["std::pair<A,B>(A,B)"]

[modules.std.symbols.cout]
kind = "object"
callable_signatures = []

[modules.rusty.symbols."os::fd::OwnedFd"]
kind = "type"
callable_signatures = []

[modules.rusty.symbols."os::fd::OwnedFd::from_raw_fd"]
kind = "function"
callable_signatures = ["OwnedFd(int)"]

[modules.rusty.symbols.srpc_adl_serialize]
kind = "function_template"
callable_signatures = ["void(const T&,Archive&)"]

[modules.rusty.symbols.srpc_adl_deserialize]
kind = "function_template"
callable_signatures = ["void(T&,Archive&)"]

[modules.rusty.symbols.srpc_sink_write]
kind = "function_template"
callable_signatures = ["void(Sink&,const uint8_t*,size_t)"]

[modules.rusty.symbols.srpc_source_read]
kind = "function_template"
callable_signatures = ["size_t(Source&,uint8_t*,size_t)"]

[modules.rusty.symbols.srpc_arc_default]
kind = "function_template"
callable_signatures = ["rusty::Arc<T>()"]

[modules.rusty.symbols.srpc_arc_copy]
kind = "function_template"
callable_signatures = ["rusty::Arc<T>(const T&)"]

[modules.rusty.symbols.srpc_holder_proxy]
kind = "function_template"
callable_signatures = ["rrr::SerializableProxy(rusty::Arc<T>)"]

[modules.rusty.symbols.srpc_factory_from_callable]
kind = "function_template"
callable_signatures = ["rusty::Function<R()>(Callable)"]
