PthreadSpinlock = "::pthread_spinlock_t"
PthreadMutex = "::pthread_mutex_t"
PthreadMutexAttr = "::pthread_mutexattr_t"
PthreadCond = "::pthread_cond_t"
PthreadCondAttr = "::pthread_condattr_t"
CFile = "FILE"
srpc_fiber_ctx = "::srpc_fiber_ctx"
srpc_fiber = "::srpc_fiber"
PromisePair = "std::pair"
QuorumDangling = "std::pair<uint16_t, int64_t>"
FrameBytes = "std::vector<uint8_t>"
TcpOutBuf = "std::vector<uint8_t>"
LegacyAddrInfo = "addrinfo"
LegacyCChar = "std::string::value_type"
LegacyCallbackWrapper = "::srpc::detail::CallbackWrapper"
LegacyChannelConnectionBase = "srpc::ChannelConnectionBase"
LegacyStdDeque = "std::deque"
LegacyTcpListener = "rusty::net::TcpListener"
LegacySocketAddrV4 = "rusty::net::SocketAddrV4"
LegacyIoErrorKind = "rusty::io::Error::Kind"
"std::marker::PhantomPinned" = "rusty::marker::PhantomPinned"
"std::os::fd::OwnedFd" = "rusty::os::fd::OwnedFd"
BinaryReadArchive = "BinaryReadArchive"
BinaryWriteArchive = "BinaryWriteArchive"
SerializableBase = "SerializableBase"
SerializableProxy = "rusty::Arc<SerializableBase>"
SerializableSharedPtrHolder = "details::SerializableSharedPtrHolder"
SrcFileCStr = "const char*"
NullableArc = "rusty::Arc"
NullableChannelConnectionProxy = "::srpc::ChannelConnectionProxy"
NullableChannelFactoryProxy = "::srpc::ChannelFactoryProxy"

[rusty]
BTreeSet = "rusty::BTreeSet"
BTreeMap = "rusty::BTreeMap"
HashSet = "rusty::HashSet"
HashMap = "rusty::HashMap"
LegacyTcpListener = "rusty::net::TcpListener"
"errors::RpcError" = "::srpc::RpcError"
LegacyRpcError = "::srpc::RpcError"
