LegacyAddrInfo = "addrinfo"
LegacyCChar = "std::string::value_type"
LegacyStdString = "std::string"
LegacyCallbackWrapper = "::rrr::detail::CallbackWrapper"
BinaryReadArchive = "BinaryReadArchive"
BinaryWriteArchive = "BinaryWriteArchive"
SerializableBase = "SerializableBase"
SerializableProxy = "SerializableProxy"
SerializableSharedPtrHolder = "details::SerializableSharedPtrHolder"

[rusty]
CallbackWrapper = "::rrr::detail::CallbackWrapper"
StdVector = "std::vector"
BinaryReadArchive = "BinaryReadArchive"
BinaryWriteArchive = "BinaryWriteArchive"
SerializableBase = "SerializableBase"
SerializableProxy = "SerializableProxy"
SerializableSharedPtrHolder = "details::SerializableSharedPtrHolder"
LoggingString = "std::string"
ReactorBoxEvent = "BoxEvent"
ReactorFiber = "Fiber"
StdPair = "std::pair"
"rrr::serializable::BinaryWriteArchive" = "rrr::BinaryWriteArchive"
"rrr::serializable::BinaryReadArchive" = "rrr::BinaryReadArchive"
