// Three-way golden proof — the TRANSLATED srpc modules at RUNTIME.
//
// The corpus (crates/srpc/tests/golden/wire_corpus.txt) is generated by
// the production C++ encoders (wire_golden_test.cc, SRPC_GOLDEN_WRITE=1)
// and already asserted byte-exact by (1) that C++ test and (2) the Rust
// crate (crates/srpc/tests/golden.rs). This test closes the triangle:
// the rusty-cpp-TRANSLATED C++ (srpc.wire.* modules emitted from the
// Rust crate) must reproduce the same bytes at runtime.
//
// Mirrors build_corpus() in golden.rs case-for-case. Also round-trips
// the V32/V64 boundary arrays through the translated deserializers
// (the SparseInt quirk paths).
//
// NOT wired into CMake yet: the translated modules are not vendored
// into the mako build. Compiled + run manually against the transpile
// spike output (see docs/srpc-rust-port.md, runtime-proof entry) —
// wire it into ctest when transpiled/ lands in-tree.

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <fstream>
#include <sstream>
#include <rusty/string.hpp>
#include <rusty/slice.hpp>
#include <map>
#include <vector>

import std;
import rusty;
import srpc.wire.archive;
import srpc.wire.serde;
import srpc.wire.frame;

namespace archive = srpc::wire::archive;
namespace serde = srpc::wire::serde;

using serde::V32;
using serde::V64;

namespace {

std::string hex(std::span<const uint8_t> bytes) {
    if (bytes.empty()) return "-";
    std::string out;
    char b[3];
    for (uint8_t x : bytes) {
        std::snprintf(b, sizeof b, "%02x", x);
        out += b;
    }
    return out;
}

template <class F>
std::string encode_case(F&& fill) {
    auto ar = archive::WriteArchive::new_();
    fill(ar);
    return hex(ar.as_bytes());
}

rusty::String rstr(const char* s) {
    return rusty::String::from(std::string_view(s));
}

// Mirrors golden.rs build_corpus() exactly — same names, same order.
std::vector<std::pair<std::string, std::string>> build_corpus() {
    std::vector<std::pair<std::string, std::string>> cs;

    // --- v32 boundaries ---------------------------------------------------
    const int32_t v32_vals[21] = {
        0, 1, -1, 63, 64, -64, -65, 8191, 8192, -8192, -8193,
        1048575, 1048576, -1048576, -1048577, 134217727, 134217728,
        -134217728, -134217729, 2147483647, INT32_MIN};
    for (size_t i = 0; i < 21; ++i) {
        cs.emplace_back("v32_" + std::to_string(i),
            encode_case([&](archive::WriteArchive& ar) {
                serde::Serialize_::serialize(V32{v32_vals[i]}, ar);
            }));
    }

    // --- v64 boundaries (incl. the 8-length quirk cases) -------------------
    const int64_t v64_vals[21] = {
        0, 1, -1, 63, -64, 8191, -8192, 1048575, -1048576,
        134217727, -134217728, 17179869183LL, -17179869184LL,
        2199023255551LL, -2199023255552LL, 281474976710655LL,
        -281474976710656LL, 36028797018963967LL, -36028797018963968LL,
        9223372036854775807LL, INT64_MIN};
    for (size_t i = 0; i < 21; ++i) {
        cs.emplace_back("v64_" + std::to_string(i),
            encode_case([&](archive::WriteArchive& ar) {
                serde::Serialize_::serialize(V64{v64_vals[i]}, ar);
            }));
    }

    // --- fixed-width scalars ----------------------------------------------
    cs.emplace_back("i8_min", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<int8_t>(-128), ar); }));
    cs.emplace_back("i16_min", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<int16_t>(-32768), ar); }));
    cs.emplace_back("i32_pattern", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<int32_t>(0x01020304), ar); }));
    cs.emplace_back("i64_pattern", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<int64_t>(0x0102030405060708LL), ar); }));
    cs.emplace_back("u8_max", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<uint8_t>(255), ar); }));
    cs.emplace_back("u16_max", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<uint16_t>(65535), ar); }));
    cs.emplace_back("u32_max", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<uint32_t>(4294967295u), ar); }));
    cs.emplace_back("u64_max", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(static_cast<uint64_t>(18446744073709551615ull), ar); }));
    cs.emplace_back("f64_pi", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(3.14159, ar); }));

    // --- strings ----------------------------------------------------------
    cs.emplace_back("str_empty", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(std::string_view(""), ar); }));
    cs.emplace_back("str_a", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(std::string_view("a"), ar); }));
    cs.emplace_back("str_hello", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(std::string_view("hello rrr wire"), ar); }));
    cs.emplace_back("str_200", encode_case([](archive::WriteArchive& ar) {
        std::string s(200, 'x');
        serde::Serialize_::serialize(std::string_view(s), ar); }));

    // --- containers -------------------------------------------------------
    cs.emplace_back("vec_i32_empty", encode_case([](archive::WriteArchive& ar) {
        auto v = rusty::Vec<int32_t>::new_();
        serde::Serialize_::serialize(v, ar); }));
    cs.emplace_back("vec_i32_123", encode_case([](archive::WriteArchive& ar) {
        auto v = rusty::Vec<int32_t>::new_();
        v.push(1); v.push(-2); v.push(3);
        serde::Serialize_::serialize(v, ar); }));
    cs.emplace_back("vec_str", encode_case([](archive::WriteArchive& ar) {
        auto v = rusty::Vec<rusty::String>::new_();
        v.push(rstr("x")); v.push(rstr("yz"));
        serde::Serialize_::serialize(v, ar); }));
    cs.emplace_back("pair_v64_str", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(std::tuple<V64, rusty::String>{V64{7}, rstr("kv")}, ar); }));

    // --- request-body composite: [v64 xid][i32 rpc_id][string arg] --------
    cs.emplace_back("request_body", encode_case([](archive::WriteArchive& ar) {
        serde::Serialize_::serialize(V64{1}, ar);
        serde::Serialize_::serialize(static_cast<int32_t>(0x1234), ar);
        serde::Serialize_::serialize(std::string_view("payload"), ar); }));

    // --- ordered map: [v64 len][k,v...] in key order -----------------------
    cs.emplace_back("map_i32_str", encode_case([](archive::WriteArchive& ar) {
        auto m = rusty::BTreeMap<int32_t, rusty::String>::new_();
        m.insert(7, rstr("seven"));
        m.insert(-1, rstr("neg"));
        serde::Serialize_::serialize(m, ar); }));

    // --- frame codec: [i32 LE (size | ext<<31)][payload] -------------------
    {
        auto frame_hex = [](std::span<const uint8_t> payload, bool ext) {
            auto out = rusty::Vec<uint8_t>::new_();
            if (!srpc::wire::frame::encode_into(out, payload, ext)) {
                std::fprintf(stderr, "encode_into refused\n");
                std::exit(2);
            }
            return hex(std::span<const uint8_t>(out.begin(), out.len()));
        };
        const uint8_t hello[5] = {'h', 'e', 'l', 'l', 'o'};
        const uint8_t xx[1] = {'x'};
        cs.emplace_back("frame_empty", frame_hex({}, false));
        cs.emplace_back("frame_hello", frame_hex(std::span<const uint8_t>(hello, 5), false));
        cs.emplace_back("frame_ext_x", frame_hex(std::span<const uint8_t>(xx, 1), true));
    }

    return cs;
}

}  // namespace

int main(int argc, char** argv) {
    const char* path = argc > 1
        ? argv[1]
        : "crates/srpc/tests/golden/wire_corpus.txt";
    std::ifstream in(path);
    if (!in) {
        std::fprintf(stderr, "cannot open corpus: %s\n", path);
        return 2;
    }

    std::map<std::string, std::string> want;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        auto sp = line.find(' ');
        want[line.substr(0, sp)] = line.substr(sp + 1);
    }

    int failures = 0;
    auto got = build_corpus();
    if (got.size() != want.size()) {
        std::fprintf(stderr, "case-count drift: corpus=%zu test=%zu\n",
                     want.size(), got.size());
        ++failures;
    }
    for (auto& [name, g] : got) {
        auto it = want.find(name);
        if (it == want.end()) {
            std::fprintf(stderr, "MISSING corpus entry: %s\n", name.c_str());
            ++failures;
        } else if (it->second != g) {
            std::fprintf(stderr, "MISMATCH %s: golden=%s translated=%s\n",
                         name.c_str(), it->second.c_str(), g.c_str());
            ++failures;
        }
    }

    // Decode round-trips through the translated deserializers (the
    // SparseInt quirk paths: v64 index 17/18 are the 8-length cases).
    {
        const int32_t v32_vals[5] = {0, -65, 8192, 2147483647, INT32_MIN};
        for (int32_t v : v32_vals) {
            auto ar = archive::WriteArchive::new_();
            serde::Serialize_::serialize(V32{v}, ar);
            auto bytes = ar.as_bytes();
            auto rd = archive::ReadArchive::new_(bytes);
            auto r = V32::deserialize(rd);
            if (!r.is_ok() || r.unwrap()._0 != v) {
                std::fprintf(stderr, "V32 round-trip FAIL at %d\n", v);
                ++failures;
            }
        }
        // Lossless sizes (1-7 bytes and the 9-byte form).
        const int64_t v64_vals[4] = {0, -1048576, -36028797018963968LL,
                                     INT64_MIN};
        for (int64_t v : v64_vals) {
            auto ar = archive::WriteArchive::new_();
            serde::Serialize_::serialize(V64{v}, ar);
            auto bytes = ar.as_bytes();
            auto rd = archive::ReadArchive::new_(bytes);
            auto r = V64::deserialize(rd);
            if (!r.is_ok() || r.unwrap()._0 != v) {
                std::fprintf(stderr, "V64 round-trip FAIL at %lld\n",
                             static_cast<long long>(v));
                ++failures;
            }
        }
        // The 8-length quirk is LOSSY by design: dump64 reports 8, so
        // the ninth payload byte never reaches the wire and decoding
        // what was actually sent returns a value 255 lower. Pinned
        // identically on the Rust side by
        // wire::varint::tests::quirk_8_length_loses_low_byte.
        {
            const int64_t quirk = 36028797018963967LL;
            auto ar = archive::WriteArchive::new_();
            serde::Serialize_::serialize(V64{quirk}, ar);
            auto bytes = ar.as_bytes();
            if (bytes.size() != 8) {
                std::fprintf(stderr, "quirk wire length %zu != 8\n", bytes.size());
                ++failures;
            }
            auto rd = archive::ReadArchive::new_(bytes);
            auto r = V64::deserialize(rd);
            if (!r.is_ok() || r.unwrap()._0 != 36028797018963712LL) {
                std::fprintf(stderr, "quirk decode FAIL: got %lld want 36028797018963712\n",
                             r.is_ok() ? static_cast<long long>(r.unwrap()._0) : -1LL);
                ++failures;
            }
        }
    }

    std::printf("translated-module golden: %zu cases, %d failures — %s\n",
                got.size(), failures, failures ? "FAIL" : "OK");
    return failures ? 1 : 0;
}
