// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-cpp-module: rrr.callback_wrapper
// provenance-input[0]-source: src/rrr/base/callback_wrapper.cpp
// provenance-input[0]-block-ids: callback_wrapper.wrapper
// provenance-input[0]-source-sha256: 377a3e5402138e266beea4ad917c443ae76f95ebb0e0dec109809029882aa458
// provenance-input[0]-rust-sha256: e29fffc6852d4fba54c5190367e35f6e6e33485ae6d4becaec136914f0c64a18
// provenance-rust-sha256: e29fffc6852d4fba54c5190367e35f6e6e33485ae6d4becaec136914f0c64a18
//
pub mod detail {
    #[repr(C)]
    pub struct CallbackWrapper<F> {
        pub inner: Option<std::sync::Arc<F>>,
    }

    impl<F> CallbackWrapper<F> {
        pub fn from_callable(callable: F) -> CallbackWrapper<F> {
            CallbackWrapper {
                inner: Some(std::sync::Arc::<F>::new(callable)),
            }
        }

        pub fn has_value(&self) -> bool {
            self.inner.is_some()
        }

        #[allow(clippy::explicit_auto_deref)]
        pub fn callable(&self) -> &F {
            &**self.inner.as_ref().unwrap()
        }
    }

    impl<F> Clone for CallbackWrapper<F> {
        fn clone(&self) -> CallbackWrapper<F> {
            CallbackWrapper {
                inner: self.inner.clone(),
            }
        }
    }

    impl<F> Default for CallbackWrapper<F> {
        fn default() -> CallbackWrapper<F> {
            CallbackWrapper { inner: None }
        }
    }
}
