// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-cpp-module: rrr.connection_metrics
// provenance-input[0]-source: src/rrr/rpc/connection_metrics.cpp
// provenance-input[0]-block-ids: connection_metrics.usings, connection_metrics.1
// provenance-input[0]-source-sha256: a3c3b64e5a81c1496b46f9e95278ec24b5a397f6803b44cb833e5f5dcf90709e
// provenance-input[0]-rust-sha256: 50acefddd39dec831c697bd91e360f71544c6c6bcb03633c6655a8b59dabcf4e
// provenance-rust-sha256: 50acefddd39dec831c697bd91e360f71544c6c6bcb03633c6655a8b59dabcf4e
//
use std::sync::atomic::AtomicU64;
use std::sync::atomic::Ordering;

#[repr(C)]
pub struct ConnectionMetrics {
    pub requests_sent_field: AtomicU64,
    pub requests_completed_field: AtomicU64,
    pub requests_failed_field: AtomicU64,
    pub requests_timed_out_field: AtomicU64,
    pub in_flight_requests_field: AtomicU64,

    pub bytes_sent_field: AtomicU64,
    pub bytes_received_field: AtomicU64,

    pub reconnect_count_field: AtomicU64,
    pub retry_attempts_field: AtomicU64,
    pub queue_dropped_requests_field: AtomicU64,
    pub circuit_open_rejections_field: AtomicU64,
    pub circuit_open_transitions_field: AtomicU64,
    pub circuit_half_open_transitions_field: AtomicU64,
    pub circuit_closed_transitions_field: AtomicU64,
    pub connect_time_ms_field: AtomicU64,

    pub total_latency_us_field: AtomicU64,
    pub min_latency_us_field: AtomicU64,
    pub max_latency_us_field: AtomicU64,
}

impl ConnectionMetrics {
    pub fn new() -> ConnectionMetrics {
        ConnectionMetrics {
            requests_sent_field: AtomicU64::new(0u64),
            requests_completed_field: AtomicU64::new(0u64),
            requests_failed_field: AtomicU64::new(0u64),
            requests_timed_out_field: AtomicU64::new(0u64),
            in_flight_requests_field: AtomicU64::new(0u64),
            bytes_sent_field: AtomicU64::new(0u64),
            bytes_received_field: AtomicU64::new(0u64),
            reconnect_count_field: AtomicU64::new(0u64),
            retry_attempts_field: AtomicU64::new(0u64),
            queue_dropped_requests_field: AtomicU64::new(0u64),
            circuit_open_rejections_field: AtomicU64::new(0u64),
            circuit_open_transitions_field: AtomicU64::new(0u64),
            circuit_half_open_transitions_field: AtomicU64::new(0u64),
            circuit_closed_transitions_field: AtomicU64::new(0u64),
            connect_time_ms_field: AtomicU64::new(0u64),
            total_latency_us_field: AtomicU64::new(0u64),
            min_latency_us_field: AtomicU64::new(u64::MAX),
            max_latency_us_field: AtomicU64::new(0u64),
        }
    }

    pub fn requests_sent(&self) -> u64 { self.requests_sent_field.load(Ordering::Relaxed) }
    pub fn requests_completed(&self) -> u64 { self.requests_completed_field.load(Ordering::Relaxed) }
    pub fn requests_failed(&self) -> u64 { self.requests_failed_field.load(Ordering::Relaxed) }
    pub fn requests_timed_out(&self) -> u64 { self.requests_timed_out_field.load(Ordering::Relaxed) }
    pub fn in_flight_requests(&self) -> u64 { self.in_flight_requests_field.load(Ordering::Relaxed) }

    pub fn bytes_sent(&self) -> u64 { self.bytes_sent_field.load(Ordering::Relaxed) }
    pub fn bytes_received(&self) -> u64 { self.bytes_received_field.load(Ordering::Relaxed) }

    pub fn reconnect_count(&self) -> u64 { self.reconnect_count_field.load(Ordering::Relaxed) }
    pub fn retry_attempts(&self) -> u64 { self.retry_attempts_field.load(Ordering::Relaxed) }
    pub fn queue_dropped_requests(&self) -> u64 { self.queue_dropped_requests_field.load(Ordering::Relaxed) }
    pub fn circuit_open_rejections(&self) -> u64 { self.circuit_open_rejections_field.load(Ordering::Relaxed) }
    pub fn circuit_open_transitions(&self) -> u64 { self.circuit_open_transitions_field.load(Ordering::Relaxed) }
    pub fn circuit_half_open_transitions(&self) -> u64 { self.circuit_half_open_transitions_field.load(Ordering::Relaxed) }
    pub fn circuit_closed_transitions(&self) -> u64 { self.circuit_closed_transitions_field.load(Ordering::Relaxed) }
    pub fn connect_time_ms(&self) -> u64 { self.connect_time_ms_field.load(Ordering::Relaxed) }

    pub fn min_latency_us(&self) -> u64 {
        let min: u64 = self.min_latency_us_field.load(Ordering::Relaxed);
        if min == u64::MAX { 0u64 } else { min }
    }
    pub fn max_latency_us(&self) -> u64 { self.max_latency_us_field.load(Ordering::Relaxed) }

    pub fn success_rate_percent(&self) -> u64 {
        let completed: u64 = self.requests_completed_field.load(Ordering::Relaxed);
        let total: u64 = self.requests_sent_field.load(Ordering::Relaxed);
        if total == 0u64 {
            return 100u64;
        }
        completed.wrapping_mul(100u64) / total
    }

    pub fn avg_latency_us(&self) -> u64 {
        let completed: u64 = self.requests_completed_field.load(Ordering::Relaxed);
        if completed == 0u64 {
            return 0u64;
        }
        self.total_latency_us_field.load(Ordering::Relaxed) / completed
    }

    pub fn uptime_ms(&self, current_time_ms: u64) -> u64 {
        let connect_time: u64 = self.connect_time_ms_field.load(Ordering::Relaxed);
        if connect_time == 0u64 {
            return 0u64;
        }
        if current_time_ms < connect_time {
            return 0u64;
        }
        current_time_ms - connect_time
    }

    pub fn record_request_sent(&self) {
        self.requests_sent_field.fetch_add(1u64, Ordering::Relaxed);
        self.in_flight_requests_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_request_completed_with_latency(&self, latency_us: u64) {
        self.requests_completed_field.fetch_add(1u64, Ordering::Relaxed);
        self.decrement_in_flight();
        self.total_latency_us_field.fetch_add(latency_us, Ordering::Relaxed);
        self.min_latency_us_field.fetch_min(latency_us, Ordering::Relaxed);
        self.max_latency_us_field.fetch_max(latency_us, Ordering::Relaxed);
    }

    pub fn record_request_completed(&self) {
        self.requests_completed_field.fetch_add(1u64, Ordering::Relaxed);
        self.decrement_in_flight();
    }

    pub fn record_request_failed(&self) {
        self.requests_failed_field.fetch_add(1u64, Ordering::Relaxed);
        self.decrement_in_flight();
    }

    pub fn record_request_timeout(&self) {
        self.requests_timed_out_field.fetch_add(1u64, Ordering::Relaxed);
        self.decrement_in_flight();
    }

    pub fn record_request_dropped(&self) {
        self.decrement_in_flight();
    }

    pub fn record_bytes_sent(&self, bytes: u64) {
        self.bytes_sent_field.fetch_add(bytes, Ordering::Relaxed);
    }

    pub fn record_bytes_received(&self, bytes: u64) {
        self.bytes_received_field.fetch_add(bytes, Ordering::Relaxed);
    }

    pub fn record_reconnect(&self) {
        self.reconnect_count_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_retry_attempt(&self) {
        self.retry_attempts_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_queue_drop(&self) {
        self.queue_dropped_requests_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_circuit_open_rejection(&self) {
        self.circuit_open_rejections_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_circuit_open_transition(&self) {
        self.circuit_open_transitions_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_circuit_half_open_transition(&self) {
        self.circuit_half_open_transitions_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_circuit_closed_transition(&self) {
        self.circuit_closed_transitions_field.fetch_add(1u64, Ordering::Relaxed);
    }

    pub fn record_connect(&self, current_time_ms: u64) {
        self.connect_time_ms_field.store(current_time_ms, Ordering::Relaxed);
    }

    pub fn reset(&self) {
        self.requests_sent_field.store(0u64, Ordering::Relaxed);
        self.requests_completed_field.store(0u64, Ordering::Relaxed);
        self.requests_failed_field.store(0u64, Ordering::Relaxed);
        self.requests_timed_out_field.store(0u64, Ordering::Relaxed);
        self.in_flight_requests_field.store(0u64, Ordering::Relaxed);
        self.bytes_sent_field.store(0u64, Ordering::Relaxed);
        self.bytes_received_field.store(0u64, Ordering::Relaxed);
        self.reconnect_count_field.store(0u64, Ordering::Relaxed);
        self.retry_attempts_field.store(0u64, Ordering::Relaxed);
        self.queue_dropped_requests_field.store(0u64, Ordering::Relaxed);
        self.circuit_open_rejections_field.store(0u64, Ordering::Relaxed);
        self.circuit_open_transitions_field.store(0u64, Ordering::Relaxed);
        self.circuit_half_open_transitions_field.store(0u64, Ordering::Relaxed);
        self.circuit_closed_transitions_field.store(0u64, Ordering::Relaxed);
        self.connect_time_ms_field.store(0u64, Ordering::Relaxed);
        self.total_latency_us_field.store(0u64, Ordering::Relaxed);
        self.min_latency_us_field.store(u64::MAX, Ordering::Relaxed);
        self.max_latency_us_field.store(0u64, Ordering::Relaxed);
    }

    pub fn decrement_in_flight(&self) {
        let _ = self.in_flight_requests_field.fetch_update(
            Ordering::Relaxed,
            Ordering::Relaxed,
            |in_flight: u64| {
                if in_flight == 0u64 {
                    None
                } else {
                    Some(in_flight - 1u64)
                }
            },
        );
    }
}
