// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-cpp-module: rrr.internal_protocol
// provenance-input[0]-source: src/rrr/rpc/internal_protocol.cpp
// provenance-input[0]-block-ids: internal_protocol.1
// provenance-input[0]-source-sha256: f41f2c428449605d235526303f3016c54e5a6f164f47f8a47c612b4e4ab5f586
// provenance-input[0]-rust-sha256: 7b20f92692a85e9c56a514bceac54295e78d3559ce0f34c69e8b1014e0a46a57
// provenance-rust-sha256: 7b20f92692a85e9c56a514bceac54295e78d3559ce0f34c69e8b1014e0a46a57
//
pub const kInternalHeartbeatRpcId: i32 = i32::MIN;
pub const kResponseHeaderExtFlag: u32 = 0x80000000;
pub const kResponseSizeMask: u32 = 0x7fffffff;

pub fn response_has_extended_header(encoded_size: i32) -> bool {
    ((encoded_size as u32) & kResponseHeaderExtFlag) != 0
}

pub fn response_payload_size(encoded_size: i32) -> i32 {
    ((encoded_size as u32) & kResponseSizeMask) as i32
}

pub fn encode_response_size(payload_size: i32, extended_header: bool) -> i32 {
    let base: u32 = (payload_size as u32) & kResponseSizeMask;
    let out: u32 = if extended_header { base | kResponseHeaderExtFlag } else { base };
    out as i32
}
