// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-manifest: src/rrr/rust-extraction.toml
// provenance-manifest-sha256: b648bc323e41e328d7bd846a4de68dfd807b0d9714bc18fde4cdd73e757bd52b
//
#![forbid(unsafe_code)]

#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod callback_wrapper;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod connection_metrics;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod errors;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod internal_protocol;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod stat;
