// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-manifest: src/rrr/rust-extraction.toml
// provenance-manifest-sha256: 44e467526d646e91b214abf3d61b767006c5cb9ba5ea6e49169acede8946954c
//
#![deny(unsafe_code)]

#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod callback_wrapper;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod completion_tracker;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod connection_metrics;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod errors;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod internal_protocol;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod rand;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod stat;
