// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-manifest: src/rrr/rust-extraction.toml
// provenance-manifest-sha256: 9d4232f0d8a845ccb46a8460c06a1ed075bd5480cacd330b57e3aab120fd1bac
//
#![forbid(unsafe_code)]

#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod callback_wrapper;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod completion_tracker;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod connection_metrics;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod errors;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod internal_protocol;
#[allow(dead_code, non_upper_case_globals, clippy::new_without_default)]
pub mod stat;
