// @generated by scripts/extract_rrr_rust.py; DO NOT EDIT.
// provenance-cpp-module: rrr.request_options
// provenance-input[0]-source: src/rrr/rpc/request_options.cpp
// provenance-input[0]-block-ids: request_options.timeout_type, request_options.0, request_options.3
// provenance-input[0]-source-sha256: c671d420a6172b63f3e542abd10ca925e076267069bb8f858e5d6ad77e0f85dc
// provenance-input[0]-rust-sha256: 53b7e0f6f394acff3c2ef724d54f1eb58389b3aa93899cbc39ea9d0e61ec1cf8
// provenance-rust-sha256: 53b7e0f6f394acff3c2ef724d54f1eb58389b3aa93899cbc39ea9d0e61ec1cf8
//
#[allow(non_camel_case_types)]
#[cfg_attr(not(any()), derive(Clone, Copy, Debug, Eq, PartialEq))]
#[repr(i32)]
pub enum TimeoutType {
    NONE = 0,
    CONNECT_TIMEOUT,
    REQUEST_TIMEOUT,
    RESPONSE_TIMEOUT,
    TOTAL_TIMEOUT,
}

#[cfg_attr(any(), cpp_import_namespace(rrr))]
use crate::rand::{randgen_rand_max, randgen_rand_raw};

#[cfg_attr(not(any()), derive(Clone, Copy, Debug, PartialEq))]
#[repr(C)]
pub struct RequestOptions {
    pub timeout_ms: u64,
    pub total_timeout_ms: u64,
    pub max_retries: u16,
    pub base_delay_ms: u16,
    pub max_delay_ms: u16,
    pub jitter_factor: f32,
    pub idempotent: bool,
}

impl RequestOptions {
    #[allow(clippy::new_without_default)]
    pub fn new() -> RequestOptions {
        RequestOptions {
            timeout_ms: 1000u64,
            total_timeout_ms: 0u64,
            max_retries: 0u16,
            base_delay_ms: 50u16,
            max_delay_ms: 5000u16,
            jitter_factor: 0.1f32,
            idempotent: false,
        }
    }

    pub fn defaults() -> RequestOptions {
        RequestOptions::new()
    }

    pub fn with_retry(max_retries: u16, timeout_ms: u64) -> RequestOptions {
        RequestOptions {
            timeout_ms,
            total_timeout_ms: 0u64,
            max_retries,
            base_delay_ms: 50u16,
            max_delay_ms: 5000u16,
            jitter_factor: 0.1f32,
            idempotent: true,
        }
    }

    pub fn idempotent_retry(max_retries: u16) -> RequestOptions {
        RequestOptions {
            timeout_ms: 1000u64,
            total_timeout_ms: 0u64,
            max_retries,
            base_delay_ms: 50u16,
            max_delay_ms: 5000u16,
            jitter_factor: 0.1f32,
            idempotent: true,
        }
    }

    pub fn no_timeout() -> RequestOptions {
        RequestOptions {
            timeout_ms: 0u64,
            total_timeout_ms: 0u64,
            max_retries: 0u16,
            base_delay_ms: 50u16,
            max_delay_ms: 5000u16,
            jitter_factor: 0.1f32,
            idempotent: false,
        }
    }

    pub fn fast() -> RequestOptions {
        RequestOptions {
            timeout_ms: 100u64,
            total_timeout_ms: 0u64,
            max_retries: 2u16,
            base_delay_ms: 10u16,
            max_delay_ms: 100u16,
            jitter_factor: 0.1f32,
            idempotent: true,
        }
    }

    pub fn patient() -> RequestOptions {
        RequestOptions {
            timeout_ms: 10000u64,
            total_timeout_ms: 60000u64,
            max_retries: 5u16,
            base_delay_ms: 500u16,
            max_delay_ms: 10000u16,
            jitter_factor: 0.1f32,
            idempotent: true,
        }
    }

    pub fn can_retry(&self, current_retry_count: u16) -> bool {
        self.idempotent && current_retry_count < self.max_retries
    }

    pub fn calculate_delay_ms(&self, attempt: u16) -> u64 {
        let mut delay: f64 = self.base_delay_ms as f64;
        let mut i: u16 = 0u16;
        while i < attempt {
            delay *= 2.0f64;
            if delay > (self.max_delay_ms as f64) {
                delay = self.max_delay_ms as f64;
                break;
            }
            i += 1u16;
        }

        if delay > (self.max_delay_ms as f64) {
            delay = self.max_delay_ms as f64;
        }

        if self.jitter_factor > 0.0f32 {
            let jitter: f64 = delay * (self.jitter_factor as f64) *
                              (((randgen_rand_raw() as f64) /
                                randgen_rand_max()) - 0.5f64);
            delay += jitter;

            if delay < 0.0f64 {
                delay = 0.0f64;
            }
        }

        delay as u64
    }

    pub fn is_total_timeout_exceeded(&self, elapsed_ms: u64) -> bool {
        self.total_timeout_ms > 0u64 && elapsed_ms >= self.total_timeout_ms
    }

    pub fn remaining_time_ms(&self, elapsed_ms: u64) -> u64 {
        if self.total_timeout_ms == 0u64 {
            return u64::MAX;
        }
        if elapsed_ms >= self.total_timeout_ms {
            return 0u64;
        }
        self.total_timeout_ms - elapsed_ms
    }
}

// NOTE: the parameter is `ty`, not `type` -- `type` is a Rust keyword and
// the DSL parser rejects it (CLAUDE.md documents this for fields; it applies
// to parameters too). C++ callers pass positionally, so the rename is local.
#[allow(unreachable_patterns)]
pub fn timeout_type_to_string(ty: TimeoutType) -> &'static str {
    match ty {
        TimeoutType::NONE => "NONE",
        TimeoutType::CONNECT_TIMEOUT => "CONNECT_TIMEOUT",
        TimeoutType::REQUEST_TIMEOUT => "REQUEST_TIMEOUT",
        TimeoutType::RESPONSE_TIMEOUT => "RESPONSE_TIMEOUT",
        TimeoutType::TOTAL_TIMEOUT => "TOTAL_TIMEOUT",
        _ => "UNKNOWN",
    }
}
